### ISSUE TITLE
Better structure for the `canyon.toml` file.

### ISSUE THREAD

**Issue by w1ll-i-code** [zerodaycode/canyon-book#1]
Hi y'all.

Let me propose a toml file that is a bit more readable for the example. It shows the entries more clearly and is easier to edit in the future. Both proposals are [100% valid toml](https://toml.io/en/v1.0.0#inline-table) files and can be parsed correctly with the toml crate.

Proposal 1:
``` toml
[[canyon_sql.datasources]]
name = 'postgres_docker'
properties.db_type = 'postgresql'
properties.username = 'postgres'
properties.password = 'postgres'
properties.host = 'localhost'
properties.port = 5438
properties.db_name = 'postgres'

[[canyon_sql.datasources]]
name = 'sqlserver_docker'
properties.db_type = 'sqlserver'
properties.username = 'sa'
properties.password = 'SqlServer-10'
properties.host = 'localhost'
properties.port = 1434
properties.db_name = 'master'
```

Proposal 2:
``` toml
[[canyon_sql.datasources]]
name = 'postgres_docker'

[canyon_sql.datasources.properties]
db_type = 'postgresql'
username = 'postgres'
password = 'postgres'
host = 'localhost'
port = 5438
db_name = 'postgres'

[[canyon_sql.datasources]]
name = 'sqlserver_docker'

[canyon_sql.datasources.properties]
db_type = 'sqlserver'
username = 'sa'
password = 'SqlServer-10'
host = 'localhost'
port = 1434
db_name = 'master'

```
